# version: '3'

# services:
#   php:
#     image: php:7.2-apache
#     volumes:
#       - .:/var/www/html
#     ports:
#       - 8000:80
#     container_name: php7.2-trial4

#   mysql:
#     platform: linux/x86_64 #Mac M1
#     image: mysql:5.7
#     volumes:
#       - /var/lib/mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD=root
#       - MYSQL_DATABASE=my_bbs
#       - MYSQL_USER=test
#       - MYSQL_PASSWORD=test
#     container_name: mysql5.7-trial4

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:5.2
#     depends_on:
#       - mysql
#     ports:
#       - 8080:80
#     environment:
#       PMA_HOST: mysql
#       PMA_USER: test
#       PMA_PASSWORD: test
#       PMA_ARBITRARY: 1
#     container_name: phpmyadmin-trial4
#     platform: linux/amd64   # 追加



version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile  # ここで使用するDockerfileを指定します。
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    container_name: php7.2-trial4

  mysql:
    platform: linux/x86_64 #Mac M1
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_bbs
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    container_name: mysql5.7-trial4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: test
      PMA_PASSWORD: test
      PMA_ARBITRARY: 1
    container_name: phpmyadmin-trial4
    platform: linux/amd64   # 追加
